package com.dgroup.exchangerates.data.model.db;

import android.util.Log;

import com.dgroup.exchangerates.data.model.ServBankCourse;
import com.dgroup.exchangerates.utils.TimeFormatter;
import com.dgroup.exchangerates.utils.Utils;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BANK_COURSE".
 */
@Entity
public class BankCourse {

    @Id
    private Long id;

    @NotNull
    private String name;
    private float usdBuy;
    private float usdSell;
    private float eurBuy;
    private float eurSell;
    private long timestamp;

    @NotNull
    private String city;
    private boolean actual;
    private String desc;

    // KEEP FIELDS - put your custom fields here
    public static BankCourse CreateFromServerCourse(ServBankCourse currentCourse, int cityCode, boolean actual) {
        BankCourse bankCourse = new BankCourse();
        bankCourse.setId((long) (currentCourse.name + cityCode).hashCode());
        Log.i("BankCourse", "id " + bankCourse.getId());
        bankCourse.setName(currentCourse.name);
        bankCourse.setCity(String.valueOf(cityCode));

        try {
            bankCourse.setUsdBuy(Utils.parseFloat(currentCourse.getUsdBuy()));
            bankCourse.setUsdSell(Utils.parseFloat(currentCourse.getUsdSell()));
            bankCourse.setEurBuy(Utils.parseFloat(currentCourse.getEurBuy()));
            bankCourse.setEurSell(Utils.parseFloat(currentCourse.getEurSell()));
        } catch (Exception e) {
            e.printStackTrace();
        }
        bankCourse.setTimestamp(TimeFormatter.getInstance().getLongServTime(currentCourse.changeTime));
        bankCourse.setActual(actual);
        return bankCourse;
    }
    // KEEP FIELDS END

    @Generated(hash = 1768446435)
    public BankCourse() {
    }

    public BankCourse(Long id) {
        this.id = id;
    }

    @Generated(hash = 981975454)
    public BankCourse(Long id, @NotNull String name, float usdBuy, float usdSell, float eurBuy, float eurSell, long timestamp, @NotNull String city, boolean actual,
            String desc) {
        this.id = id;
        this.name = name;
        this.usdBuy = usdBuy;
        this.usdSell = usdSell;
        this.eurBuy = eurBuy;
        this.eurSell = eurSell;
        this.timestamp = timestamp;
        this.city = city;
        this.actual = actual;
        this.desc = desc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public float getUsdBuy() {
        return usdBuy;
    }

    public void setUsdBuy(float usdBuy) {
        this.usdBuy = usdBuy;
    }

    public float getUsdSell() {
        return usdSell;
    }

    public void setUsdSell(float usdSell) {
        this.usdSell = usdSell;
    }

    public float getEurBuy() {
        return eurBuy;
    }

    public void setEurBuy(float eurBuy) {
        this.eurBuy = eurBuy;
    }

    public float getEurSell() {
        return eurSell;
    }

    public void setEurSell(float eurSell) {
        this.eurSell = eurSell;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    @NotNull
    public String getCity() {
        return city;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCity(@NotNull String city) {
        this.city = city;
    }

    public boolean getActual() {
        return actual;
    }

    public void setActual(boolean actual) {
        this.actual = actual;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
