package com.dgroup.exchangerates.data.model.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CRYPTO_MARKET_CURRENCY_INFO".
 */
@Entity
public class CryptoMarketCurrencyInfo {

    @Id
    private long id;
    private String coinId;
    private String name;
    private String symbol;
    private int rank;
    private String icon;
    private float price_usd;
    private float price_btc;
    private float volume_usd_24h;
    private double market_cap_usd;
    private double available_supply;
    private double total_supply;
    private double max_supply;
    private float percent_change_1h;
    private float percent_change_24h;
    private float percent_change_7d;
    private long last_updated;
    private String graph;

    @Transient
    private boolean redrawGraph;

    @Generated(hash = 1640737522)
    public CryptoMarketCurrencyInfo() {
    }

    public CryptoMarketCurrencyInfo(long id) {
        this.id = id;
    }

    @Generated(hash = 851729538)
    public CryptoMarketCurrencyInfo(long id, String coinId, String name, String symbol, int rank, String icon, float price_usd, float price_btc, float volume_usd_24h, double market_cap_usd, double available_supply, double total_supply, double max_supply, float percent_change_1h, float percent_change_24h, float percent_change_7d, long last_updated, String graph) {
        this.id = id;
        this.coinId = coinId;
        this.name = name;
        this.symbol = symbol;
        this.rank = rank;
        this.icon = icon;
        this.price_usd = price_usd;
        this.price_btc = price_btc;
        this.volume_usd_24h = volume_usd_24h;
        this.market_cap_usd = market_cap_usd;
        this.available_supply = available_supply;
        this.total_supply = total_supply;
        this.max_supply = max_supply;
        this.percent_change_1h = percent_change_1h;
        this.percent_change_24h = percent_change_24h;
        this.percent_change_7d = percent_change_7d;
        this.last_updated = last_updated;
        this.graph = graph;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getCoinId() {
        return coinId;
    }

    public void setCoinId(String coinId) {
        this.coinId = coinId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public int getRank() {
        return rank;
    }

    public void setRank(int rank) {
        this.rank = rank;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    public float getPrice_usd() {
        return price_usd;
    }

    public void setPrice_usd(float price_usd) {
        this.price_usd = price_usd;
    }

    public float getPrice_btc() {
        return price_btc;
    }

    public void setPrice_btc(float price_btc) {
        this.price_btc = price_btc;
    }

    public float getVolume_usd_24h() {
        return volume_usd_24h;
    }

    public void setVolume_usd_24h(float volume_usd_24h) {
        this.volume_usd_24h = volume_usd_24h;
    }

    public double getMarket_cap_usd() {
        return market_cap_usd;
    }

    public void setMarket_cap_usd(double market_cap_usd) {
        this.market_cap_usd = market_cap_usd;
    }

    public double getAvailable_supply() {
        return available_supply;
    }

    public void setAvailable_supply(double available_supply) {
        this.available_supply = available_supply;
    }

    public double getTotal_supply() {
        return total_supply;
    }

    public void setTotal_supply(double total_supply) {
        this.total_supply = total_supply;
    }

    public double getMax_supply() {
        return max_supply;
    }

    public void setMax_supply(double max_supply) {
        this.max_supply = max_supply;
    }

    public float getPercent_change_1h() {
        return percent_change_1h;
    }

    public void setPercent_change_1h(float percent_change_1h) {
        this.percent_change_1h = percent_change_1h;
    }

    public float getPercent_change_24h() {
        return percent_change_24h;
    }

    public void setPercent_change_24h(float percent_change_24h) {
        this.percent_change_24h = percent_change_24h;
    }

    public float getPercent_change_7d() {
        return percent_change_7d;
    }

    public void setPercent_change_7d(float percent_change_7d) {
        this.percent_change_7d = percent_change_7d;
    }

    public long getLast_updated() {
        return last_updated;
    }

    public void setLast_updated(long last_updated) {
        this.last_updated = last_updated;
    }

    public String getGraph() {
        return graph;
    }

    public void setGraph(String graph) {
        this.graph = graph;
    }

    // KEEP METHODS - put your custom methods here
    public boolean getAndClearRedraw() {
        if(redrawGraph){
            redrawGraph = false;
            return true;
        }
        return false;
    }

    public void setRedrawGraph(boolean redrawGraph) {
        this.redrawGraph = redrawGraph;
    }
    // KEEP METHODS END

}
